name: Pytest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Tests with pytest
        run: |
          pytest --cov=evolution